// 从 wordlists 的 data/zh 生成 server/seed/words_zh.sql（COPY 文本格式）。
//
//   definitions.json  词/字 -> [拼音, [[读音, [英文释义…]], …]]   (CC-CEDICT)
//   字义.json          汉字 -> 英文 gloss                          (Unihan)
//   HSK词汇.json       分 7 级，词 -> [[拼音, 词性], …]
//   HSK汉字.json       分认读/书写段，段 -> [字…]
//
// 落库口径：
//   pinyin = HSK 拼音；senses = [[词性, [英文释义]], …]（与 en 同结构）
//   单字（含既是字又是词）→ 释义取 字义.json 的 Unihan gloss
//   多字词               → 释义取 definitions.json（CC-CEDICT，各读音摊平去重）
//   词性只为对齐结构（前端不显示）；tag = HSK 等级（字用认读字级）。
//
// 用法：node server/scripts/build-zh-seed.mjs [wordlists目录]
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const wordlists = resolve(process.argv[2] ?? resolve(here, '../../../wordlists'))
const zh = resolve(wordlists, 'data/zh')
const out = resolve(here, '../seed/words_zh.sql')

const read = (name) => {
  const p = resolve(zh, name)
  if (!existsSync(p)) {
    console.error(`[build-zh-seed] 找不到 ${p}`)
    process.exit(1)
  }
  return JSON.parse(readFileSync(p, 'utf8'))
}
const stripMeta = (o) => Object.fromEntries(Object.entries(o).filter(([k]) => k !== '_meta'))

const WORD_LEVEL = {
  一级: 'HSK1',
  二级: 'HSK2',
  三级: 'HSK3',
  四级: 'HSK4',
  五级: 'HSK5',
  六级: 'HSK6',
  '七—九级': 'HSK7-9',
}
const charLevel = (section) => WORD_LEVEL[section.replace(/认读字|书写字/g, '')]

const defs = stripMeta(read('definitions.json'))
const ziyi = stripMeta(read('字义.json'))
const hskw = stripMeta(read('HSK词汇.json'))
const hskc = stripMeta(read('HSK汉字.json'))

/** word -> Set<tag> / Set<词性> */
const wordTags = new Map()
const wordPos = new Map()
for (const [section, words] of Object.entries(hskw)) {
  const tag = WORD_LEVEL[section]
  if (!tag) continue
  for (const [word, records] of Object.entries(words)) {
    let tagSet = wordTags.get(word)
    if (!tagSet) {
      tagSet = new Set()
      wordTags.set(word, tagSet)
    }
    tagSet.add(tag)
    const pos = wordPos.get(word) ?? new Set()
    for (const rec of records) {
      const p = Array.isArray(rec) ? rec[1] : ''
      if (typeof p === 'string' && p) for (const x of p.split('、')) if (x.trim()) pos.add(x.trim())
    }
    wordPos.set(word, pos)
  }
}

/** char -> tag（只取认读等级） */
const charTags = new Map()
const charSet = new Set()
for (const [section, chars] of Object.entries(hskc)) {
  for (const ch of chars) charSet.add(ch)
  if (!section.includes('认读')) continue
  const tag = charLevel(section)
  if (tag) for (const ch of chars) charTags.set(ch, tag)
}
const wordSet = new Set(
  Object.values(hskw).flatMap((words) => Object.keys(words)),
)

/** 摊平 definitions.json 各读音的释义并去重 */
function flatDefs(senses) {
  const out = []
  for (const group of senses ?? []) {
    for (const d of group?.[1] ?? []) if (!out.includes(d)) out.push(d)
  }
  return out
}

const esc = (v) => {
  if (v === null || v === undefined) return '\\N'
  return String(v)
    .replace(/\\/g, '\\\\')
    .replace(/\t/g, '\\t')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
}
const arr = (set) => (set && set.size ? `{${[...set].join(',')}}` : null)

const lines = []
let charDefs = 0
let wordDefs = 0
let noDefs = 0
for (const [word, entry] of Object.entries(defs)) {
  const isChar = charSet.has(word)
  const isWord = wordSet.has(word)
  const kind = isChar && isWord ? 'both' : isChar ? 'char' : 'word'
  const pinyin = entry[0] || null

  // 单字（含 both）→ Unihan gloss；多字词 → CC-CEDICT
  let list
  if (isChar && ziyi[word]) {
    list = [ziyi[word]]
    charDefs++
  } else {
    list = flatDefs(entry[1])
    if (list.length) wordDefs++
  }
  if (list.length === 0) noDefs++

  const pos = [...(wordPos.get(word) ?? [])].join('、')
  const tags = new Set([
    ...(wordTags.get(word) ?? []),
    ...(charTags.has(word) ? [charTags.get(word)] : []),
  ])
  const senses = [[pos, list]]

  lines.push(
    ['zh', word, arr(tags), pinyin, JSON.stringify(senses), kind]
      .map(esc)
      .join('\t'),
  )
}

const header = `--
-- generated by server/scripts/build-zh-seed.mjs
-- 来源: wordlists data/zh（CC-CEDICT / Unihan / HSK 大纲）
--
SET client_encoding = 'UTF8';
COPY public.words (lang, word, tags, pinyin, senses, kind) FROM stdin;
`
writeFileSync(out, `${header}${lines.join('\n')}\n\\.\n`, 'utf8')
console.log(
  `[build-zh-seed] ${lines.length} 行 -> ${out}（字 gloss ${charDefs}，词释义 ${wordDefs}，无释义 ${noDefs}）`,
)
